### ISSUE TITLE
'dynamic_config' is not a known MakeMaker parameter name.

### ISSUE THREAD

**Issue by szabgab** [ThisUsedToBeAnEmail/String-Mask#1]
After cloning the repository I got:

```
$ perl Makefile.PL 
WARNING: dynamic_config is not a known parameter.
'dynamic_config' is not a known MakeMaker parameter name.
Generating a Unix-style Makefile
Writing Makefile for String::Mask
Writing MYMETA.yml and MYMETA.json
```

I had  ExtUtils::MakeMaker  version 7.34

I upgraded to 7.50 but I still get the same, apparently warning.

**Comment by ThisUsedToBeAnEmail** [comment]
I'm unsure on how to correctly define dynamic_config but I believe it's needed for metacpan to not show the 'and possibly others' message under the list of dependencies. 

<img width="233" alt="Screenshot 2020-10-26 at 17 04 10" src="https://user-images.githubusercontent.com/16151791/97203954-666afa00-17ad-11eb-9975-c44933632a51.png">

**Comment by szabgab** [comment]
Hmm, I don't know what does that even mean, but I have just asked it: https://github.com/metacpan/metacpan-web/issues/2400

**Comment by szabgab** [comment]
After searching for examples I think it needs to be written as:

```
META_ADD => { 
   dynamic_config => 0,
}
```

Oh I see there is already a fix with META_MERGE. Thanks for the help.

**Comment by ThisUsedToBeAnEmail** [comment]
If you pull the latest master, this should now be resolved.
